apiVersion: v1
kind: Service
metadata:
  name: wenshu-agent
  namespace: wenshu-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wenshu-agent
  ports:
    - name: http
      port: 80
      targetPort: http
